# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9.1
whitelist: &whitelist
  paths:
    - .npmignore
    - coverage/*
    - dist/*
    - node_modules/*
    - src/*
    - test/*
    - CODE_OF_CONDUCT.md
    - LICENSE.md
    - package.json
    - README.md
    - tsconfig.json
    - tslint.json
version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run build
      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run test
      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist
workflows: 
  version: 2
  build:
    jobs:
      - checkout:
          filters:
            branches:
              ignore:
                - devs
      - test:
          requires:
            - checkout
          filters:
            branches:
              ignore:
                - devs
      - build:
          requires:
            - test

